// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Feed struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Url           string         `json:"url"`
	UserID        int64          `json:"user_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	LastFetchedAt sql.NullInt64  `json:"last_fetched_at"`
	Description   sql.NullString `json:"description"`
	ImageUrl      sql.NullString `json:"image_url"`
	ImageText     sql.NullString `json:"image_text"`
	Language      sql.NullString `json:"language"`
}

type FeedFollow struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	FeedID    int64       `json:"feed_id"`
	CreatedAt int64       `json:"created_at"`
	UpdatedAt int64       `json:"updated_at"`
	Foreign   interface{} `json:"foreign"`
}

type Post struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	FeedID      int64          `json:"feed_id"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	PublishedAt int64          `json:"published_at"`
	Content     sql.NullString `json:"content"`
}

type User struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UsersBookmark struct {
	ID        int64 `json:"id"`
	PostID    int64 `json:"post_id"`
	UserID    int64 `json:"user_id"`
	CreatedAt int64 `json:"created_at"`
}
